version: '3.4'

services:
  publisher:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  subscriber:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

