version: '3.4'

services:
  publisher:
    image: ${DOCKER_REGISTRY-}publisher
    build:
      context: .
      dockerfile: Publisher/Dockerfile
    networks:
      - service-network
    ports:
      - "5001:80"

  publisher-dapr:
    image: "daprio/daprd:latest"
    command: [ "./daprd", 
    "-app-id", "publisher", 
    "-components-path", "/components",
    "-app-port", "80" ]
    volumes:
        - "./components/:/components"
    depends_on:
        - publisher
    network_mode: "service:publisher"

  subscriber:
    image: ${DOCKER_REGISTRY-}subscriber
    build:
      context: .
      dockerfile: Subscriber/Dockerfile
    networks:
      - service-network
    ports:
      - "5002:80"

  subscriber-dapr:
    image: "daprio/daprd:latest"
    command: [ "./daprd", 
    "-app-id", "subscriber", 
    "-components-path", "/components",
    "-app-port", "80" ]
    volumes:
        - "./components/:/components"
    depends_on:
      - subscriber
    network_mode: "service:subscriber"

  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"
    networks:
      - service-network

networks:
    service-network:
